### ISSUE TITLE
Scalapb plugins

### ISSUE THREAD

**Issue by borissmidt** [scalapb/gradle-demo#3]
The example doesn't really show how you can enable plugins for scalapb, for example the [ZIO](https://github.com/scalapb/zio-grpc) or AKKA plugin.

**Comment by thesamet** [comment]
Hi @borissmidt , for zio , we publish [https://repo1.maven.org/maven2/com/thesamet/scalapb/zio-grpc/protoc-gen-zio/0.5.0/](protoc-gen-zio) similarly to `protoc-gen-scala` - can you try to make it work and report here? If possible, please send a PR that shows an example of adding zio-grpc to the example build and make it commented out so interested users can uncomment. Thank you!

**Comment by borissmidt** [comment]
Ah so all scalapb plugins are packaged into a runable generator that can run independent with protoc.

**Comment by thesamet** [comment]
All plugins under ScalaPB org are published with a runnable generator. For akka-grpc, there's a different approach: https://doc.akka.io/docs/akka-grpc/current/buildtools/gradle.html

**Comment by aviadsTraiana** [comment]
Hi @thesamet , 
I would like to help.. can't push to a new branch in this repo so I pushed it to my own...
https://github.com/aviadsTraiana/zio-grpc-demo
the build fails on:
```
zio_grpc is not a member of package scalapb
```

can you please help me figure out what is wrong?

**Comment by thesamet** [comment]
It looks like you are missing the zio-grpc runtime dependency: https://mvnrepository.com/artifact/com.thesamet.scalapb.zio-grpc/zio-grpc-core

Also, the ScalaPB version and zio-grpc versions are misaligned. zio-grpc 0.5.0 goes with ScalaPB 0.11.x

**Comment by aviadsTraiana** [comment]
@thesamet still having issues with compilation after aligning versions and adding the dependency:
https://github.com/aviadsTraiana/zio-grpc-demo/commit/8561484ef5e936b265c1d99de8cd1ae0f28cd2a7

**Comment by thesamet** [comment]
Please specify the issues.

**Comment by aviadsTraiana** [comment]
yes, sorry- 
```
 Task :compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/ziopb/scalapb/protos/demo/ZioDemo.scala:25: object GreeterGrpc is not a member of package scalapb.protos.demo
            _root_.io.grpc.ServerServiceDefinition.builder(scalapb.protos.demo.GreeterGrpc.SERVICE)
                                                                               ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/ziopb/scalapb/protos/demo/ZioDemo.scala:27: object GreeterGrpc is not a member of package scalapb.protos.demo
              scalapb.protos.demo.GreeterGrpc.METHOD_SAY_HELLO,
                                  ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/ziopb/scalapb/protos/demo/ZioDemo.scala:60: object GreeterGrpc is not a member of package scalapb.protos.demo
        channel, scalapb.protos.demo.GreeterGrpc.METHOD_SAY_HELLO, options,
                                     ^
three errors found

> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 19s
6 actionable tasks: 6 executed
~/git/github/scalapb/gradle-demo on zio_demo*
$ gw clean build

> Task :compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/ziopb/scalapb/protos/demo/ZioDemo.scala:25: object GreeterGrpc is not a member of package scalapb.protos.demo
            _root_.io.grpc.ServerServiceDefinition.builder(scalapb.protos.demo.GreeterGrpc.SERVICE)
                                                                               ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/ziopb/scalapb/protos/demo/ZioDemo.scala:27: object GreeterGrpc is not a member of package scalapb.protos.demo
              scalapb.protos.demo.GreeterGrpc.METHOD_SAY_HELLO,
                                  ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/ziopb/scalapb/protos/demo/ZioDemo.scala:60: object GreeterGrpc is not a member of package scalapb.protos.demo
        channel, scalapb.protos.demo.GreeterGrpc.METHOD_SAY_HELLO, options,
                                     ^
three errors found
```

**Comment by thesamet** [comment]
Adding `option 'grpc'` to the `scalapb` generator parameters should fix it.

**Comment by aviadsTraiana** [comment]
I think it did fix it for the problem above , but still failing:
https://github.com/aviadsTraiana/zio-grpc-demo/blob/zio_demo/build.gradle#L64
```
 Task :compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/Person.scala:86: object Demo is not a member of package scalapb.protos
object Person extends scalapb.GeneratedMessageCompanion[scalapb.protos.demo.Person] with scalapb.JavaProtoSupport[scalapb.protos.demo.Person, scalapb.protos.Demo.Person] {
                                                                                                                                                             ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloRequest.scala:68: object Demo is not a member of package scalapb.protos
object HelloRequest extends scalapb.GeneratedMessageCompanion[scalapb.protos.demo.HelloRequest] with scalapb.JavaProtoSupport[scalapb.protos.demo.HelloRequest, scalapb.protos.Demo.HelloRequest] {
                                                                                                                                                                               ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloReply.scala:68: object Demo is not a member of package scalapb.protos
object HelloReply extends scalapb.GeneratedMessageCompanion[scalapb.protos.demo.HelloReply] with scalapb.JavaProtoSupport[scalapb.protos.demo.HelloReply, scalapb.protos.Demo.HelloReply] {
                                                                                                                                                                         ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/DemoProto.scala:31: object Demo is not a member of package scalapb.protos
    scalapb.protos.Demo.getDescriptor()
                   ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloRequest.scala:69: object Demo is not a member of package scalapb.protos
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scalapb.protos.demo.HelloRequest] with scalapb.JavaProtoSupport[scalapb.protos.demo.HelloRequest, scalapb.protos.Demo.HelloRequest] = this
                                                                                                                                                                                    ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/GreeterGrpc.scala:9: could not find implicit value for parameter companion: scalapb.GeneratedMessageCompanion[scalapb.protos.demo.HelloRequest]
      .setRequestMarshaller(_root_.scalapb.grpc.Marshaller.forMessage[scalapb.protos.demo.HelloRequest])
                                                                     ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloReply.scala:69: object Demo is not a member of package scalapb.protos
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scalapb.protos.demo.HelloReply] with scalapb.JavaProtoSupport[scalapb.protos.demo.HelloReply, scalapb.protos.Demo.HelloReply] = this
                                                                                                                                                                                ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloReply.scala:70: object Demo is not a member of package scalapb.protos
  def toJavaProto(scalaPbSource: scalapb.protos.demo.HelloReply): scalapb.protos.Demo.HelloReply = {
                                                                                 ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloReply.scala:71: object Demo is not a member of package scalapb.protos
    val javaPbOut = scalapb.protos.Demo.HelloReply.newBuilder
                                   ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloReply.scala:75: object Demo is not a member of package scalapb.protos
  def fromJavaProto(javaPbSource: scalapb.protos.Demo.HelloReply): scalapb.protos.demo.HelloReply = scalapb.protos.demo.HelloReply(
                                                 ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloRequest.scala:70: object Demo is not a member of package scalapb.protos
  def toJavaProto(scalaPbSource: scalapb.protos.demo.HelloRequest): scalapb.protos.Demo.HelloRequest = {
                                                                                   ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloRequest.scala:71: object Demo is not a member of package scalapb.protos
    val javaPbOut = scalapb.protos.Demo.HelloRequest.newBuilder
                                   ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/HelloRequest.scala:75: object Demo is not a member of package scalapb.protos
  def fromJavaProto(javaPbSource: scalapb.protos.Demo.HelloRequest): scalapb.protos.demo.HelloRequest = scalapb.protos.demo.HelloRequest(
                                                 ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/Person.scala:87: object Demo is not a member of package scalapb.protos
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[scalapb.protos.demo.Person] with scalapb.JavaProtoSupport[scalapb.protos.demo.Person, scalapb.protos.Demo.Person] = this
                                                                                                                                                                        ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/Person.scala:88: object Demo is not a member of package scalapb.protos
  def toJavaProto(scalaPbSource: scalapb.protos.demo.Person): scalapb.protos.Demo.Person = {
                                                                             ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/Person.scala:89: object Demo is not a member of package scalapb.protos
    val javaPbOut = scalapb.protos.Demo.Person.newBuilder
                                   ^
/Users/aviads/git/github/scalapb/gradle-demo/build/generated/source/proto/main/scalapb/scalapb/protos/demo/Person.scala:94: object Demo is not a member of package scalapb.protos
  def fromJavaProto(javaPbSource: scalapb.protos.Demo.Person): scalapb.protos.demo.Person = scalapb.protos.demo.Person(
                                                 ^
17 errors found

> Task :compileScala FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileScala'.
> Compilation failed

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
```

**Comment by thesamet** [comment]
You have `option 'java_conversions'` enabled but disabled the Java generator.

**Comment by thesamet** [comment]
The option tells ScalaPB to generate code that converts between Java and Scala protos, but it relies on the Java code to be generated or somehow available at compile time.

**Comment by aviadsTraiana** [comment]
ohh oops! that was dumb... yeah it compiles now :)
Thanks you!!

**Comment by thesamet** [comment]
Fantastic, can you open a pull request to a new branch named `zio` in this repo, and that would serve as an example/documentation to address this ticket?

**Comment by aviadsTraiana** [comment]
sure :) I just need permissions.

```
git push --set-upstream origin zio
ERROR: Permission to scalapb/gradle-demo.git denied to aviadsTraiana.
fatal: Could not read from remote repository.

```

**Comment by thesamet** [comment]
You only need to send a pull request over github, not to push directly to the branch.

**Comment by aviadsTraiana** [comment]
oh wasn't aware there is an option with fork.. learned a few things today.

**Comment by thesamet** [comment]
Closing the issue now that we have a working example in the [zio branch](https://github.com/scalapb/gradle-demo/tree/zio).
